// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aqitjhaotpautjywoeys.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFxaXRqaGFvdHBhdXRqeXdvZXlzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjU1NzE3MTIsImV4cCI6MjA4MTE0NzcxMn0.CS8QpR9kVzHC6jGnkwV3onm-HiVNWyxF8rryfK2p87o";

// Check if localStorage is available (may be blocked in iframes/sandboxed contexts)
const getStorage = () => {
  try {
    const test = '__storage_test__';
    window.localStorage.setItem(test, test);
    window.localStorage.removeItem(test);
    return localStorage;
  } catch {
    // Memory storage fallback
    const memoryStorage: Record<string, string> = {};
    return {
      getItem: (key: string) => memoryStorage[key] ?? null,
      setItem: (key: string, value: string) => { memoryStorage[key] = value; },
      removeItem: (key: string) => { delete memoryStorage[key]; },
    };
  }
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Create a mock client if Supabase is not configured
const createSupabaseClient = () => {
  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    // Return a mock client that won't crash the app
    console.warn('Supabase not configured. Some features may not work.');
    return null as unknown as ReturnType<typeof createClient<Database>>;
  }
  
  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: getStorage(),
      persistSession: true,
      autoRefreshToken: true,
    }
  });
};

export const supabase = createSupabaseClient();
